Remove ./tools/fetch-tags invocation from Makefile
This invocation causes problems when make targets are executed in the
build image container (`BUILD_IN_CONTAINER=true`), e.g. the `yacc`
target, because git tries to fetch tags from `origin` using ssh, causing
error message like these:

```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
```

This is because local ssh keys are not mounted into the build container.

In order not to break CI builds
(https://github.com/grafana/loki/pull/8232) we need to manually fetch
the tags as the first step in release pipelines. This is added to the
Drone configuration.

Signed-off-by: Christian Haudum <christian.haudum@gmail.com>