promtail: fix syslog udp messages never processed (stream-based parser)
Prior to this patch, incoming UDP syslogs would only be sent to promtail
targets all at once when promtail shut down. The ultimate cause seems to
be that `go-syslog`'s stream parsers are not emitting any messages until
the input stream is closed, even after newline-delimiting the messages.
This patch closes those streams after one packet's contents and a
newline are sent.

% go test -run SyslogTarget
level=info msg="syslog listening on address" address=127.0.0.1:65036 protocol=tcp tls=false
level=info address=127.0.0.1:65036 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:65038 protocol=tcp tls=false
level=info address=127.0.0.1:65038 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:53197 protocol=udp
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:53197: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:62837 protocol=udp
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:62837: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:54772 protocol=udp
level=warn msg="error parsing syslog stream" err="found ILLEGAL(\n), expecting a MSGLEN"
level=warn msg="error parsing syslog stream" err="found ILLEGAL(\n), expecting a MSGLEN"
level=warn msg="error parsing syslog stream" err="found ILLEGAL(\n), expecting a MSGLEN"
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:54772: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
--- FAIL: TestSyslogTarget (3.12s)
    --- FAIL: TestSyslogTarget/udp_newline_separated (1.03s)
        syslogtarget_test.go:489:
            	Error Trace:	/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/syslogtarget_test.go:489
            	Error:      	Not equal:
            	           	expected: "An application event log entry..."
            	           	actual  : "An application event log entry...\n"

            	           	Diff:
            	           	--- Expected
            	           	+++ Actual
            	           	@@ -1 +1,2 @@
            	           	An application event log entry...
            	           	+
            	Test:       	TestSyslogTarget/udp_newline_separated
level=info msg="syslog listening on address" address=127.0.0.1:65040 protocol=tcp tls=false
level=info address=127.0.0.1:65040 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:65042 protocol=tcp tls=false
level=info address=127.0.0.1:65042 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:65046 protocol=tcp tls=true
level=warn msg="error parsing syslog stream" err="expecting a RFC3339MICRO timestamp or a nil value [col 7]"
level=warn msg="error parsing syslog stream" err="expecting a msgid (from 1 to max 32 US-ASCII characters) or a nil value [col 42]"
level=info address=127.0.0.1:65046 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:65048 protocol=tcp tls=true
level=warn msg="error parsing syslog stream" err="expecting a RFC3339MICRO timestamp or a nil value [col 7]"
level=warn msg="error parsing syslog stream" err="expecting a msgid (from 1 to max 32 US-ASCII characters) or a nil value [col 42]"
level=info address=127.0.0.1:65048 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:65050 protocol=tcp tls=true
level=warn msg="error initializing syslog stream" err="tls: client didn't provide a certificate"
level=info address=127.0.0.1:65050 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:65053 protocol=tcp tls=true
level=warn msg="error initializing syslog stream" err="tls: client didn't provide a certificate"
level=info address=127.0.0.1:65053 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:65056 protocol=tcp tls=false
level=warn msg="error initializing syslog stream" err="invalid or unsupported framing. first byte: 'x'"
level=info address=127.0.0.1:65056 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:65058 protocol=tcp tls=false
level=info address=127.0.0.1:65058 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:65060 protocol=tcp tls=false
level=warn msg="error initializing syslog stream" err="read tcp 127.0.0.1:65060->127.0.0.1:65061: i/o timeout"
level=info address=127.0.0.1:65060 msg="syslog server shutting down" protocol=tcp err="context canceled"
FAIL
exit status 1
FAIL	github.com/grafana/loki/clients/pkg/promtail/targets/syslog	3.767s

% go test -run \^\# -bench SyslogTarget -benchtime 20ms -count 3
goos: darwin
goarch: arm64
pkg: github.com/grafana/loki/clients/pkg/promtail/targets/syslog
Benchmark_SyslogTarget/tcp_octetcounting-10         	    414	    54300 ns/op	  28766 B/op	    360 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	    453	    69232 ns/op	  28758 B/op	    360 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	    402	    67254 ns/op	  28764 B/op	    360 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	    180	   136459 ns/op	 151979 B/op	    742 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	    154	   134058 ns/op	 151945 B/op	    741 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	    166	   127600 ns/op	 151845 B/op	    741 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	    238	    96841 ns/op	  97031 B/op	    662 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	    230	    96199 ns/op	  96994 B/op	    660 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	    223	    96208 ns/op	  96888 B/op	    660 allocs/op
PASS
ok  	github.com/grafana/loki/clients/pkg/promtail/targets/syslog	1.198s