chore(schema-v13): Fix series store schema creation for v13 (#10348)
The creation of a series store schema failed when using v13 schema version.

**Special notes for your reviewer**:

When adding the `v13` to the series store test cases
(`pkg/storage/stores/series/series_store_test.go`) they fail. Example
error:

```
=== RUN   TestSeriesStore_LabelValuesForMetricName/foo_/_toms_/_v13_/_store
    series_store_test.go:700: ========= Running labelValues with metricName foo with labelName toms with schema v13
    series_store_test.go:93:
        	Error Trace:	/home/christian/sandbox/grafana/loki/pkg/storage/stores/series/series_store_test.go:93
        	            				/home/christian/sandbox/grafana/loki/pkg/storage/stores/series/series_store_test.go:77
        	            				/home/christian/sandbox/grafana/loki/pkg/storage/stores/series/series_store_test.go:702
        	Error:      	Received unexpected error:
        	            	invalid schema version
        	Test:       	TestSeriesStore_LabelValuesForMetricName/foo_/_toms_/_v13_/_store
=== RUN   TestSeriesStore_LabelValuesForMetricName/foo_/_toms_/_v13_/_cached_store
    series_store_test.go:700: ========= Running labelValues with metricName foo with labelName toms with schema v13
    series_store_test.go:93:
        	Error Trace:	/home/christian/sandbox/grafana/loki/pkg/storage/stores/series/series_store_test.go:93
        	            				/home/christian/sandbox/grafana/loki/pkg/storage/stores/series/series_store_test.go:77
        	            				/home/christian/sandbox/grafana/loki/pkg/storage/stores/series/series_store_test.go:702
        	Error:      	Received unexpected error:
        	            	invalid schema version
        	Test:       	TestSeriesStore_LabelValuesForMetricName/foo_/_toms_/_v13_/_cached_store

```

Signed-off-by: Christian Haudum <christian.haudum@gmail.com>
(cherry picked from commit 210c937c414c3623c5770d6c3c237186db12fa75)