chore(ci): Fix `lint` target in Makefile
The quotes in variable definition are considered literals, and therefore
the target constructs a command that looks like this

golangci-lint run -v "--timeout=900 --build-tags=linux,promtail_journal_enabled"

rather than this

golangci-lint run -v --timeout=15m --build-tags=linux,promtail_journal_enabled

resulting in an error like that

Error: invalid argument "15m --build-tags=linux,promtail_journal_enabled" for "--timeout" flag: time: unknown unit "m --build-tags=linux,promtail_journal_enabled" in duration "15m --build-tags=linux,promtail_journal_enabled"