Re-run drone
Seeing if this error is consistent, since I can't reproduce locally:
```
--- FAIL: TestSingleBinaryIngestQuery (0.01s)
    loki_single_binary_test.go:28:
        	Error Trace:	/src/loki/integration/loki_single_binary_test.go:28
        	Error:      	Received unexpected error:
        	            	error starting component all: error initialising module: server: listen tcp :45253: bind: address already in use
        	Test:       	TestSingleBinaryIngestQuery
```