Fix flaky test TestTCPErrs
This test was failing occasionally in CI due to racing wall-clock timers. In this PR I propose that we stop mocking out an http server and instead mock out the http transport to return the error that would've been returned by the error case.

We could also have tweaked the numbers to make it less likely for timers to trigger in the wrong order - I'd be happy to change to that approach if that's what people prefer.

Another approach I tried was using testing/synctest, but wasn't able to get it working because then the timer would trigger at exactly the deadline and we'd end up in the wrong branch here https://github.com/golang/go/blob/go1.26.5/src/net/http/client.go#L372 because of the strict inequality. In reality we'd wave up slightly after the deadline rather than exactly at that moment.

Flaky test failure I've seen in CI:
```
  === FAIL: pkg/storage/chunk/client/gcp TestTCPErrs/transport_connect_timeout_exceeded,_retryable (0.04s)
      gcs_object_client_test.go:232:
              Error Trace:    /__w/loki/loki/release/pkg/storage/chunk/client/gcp/gcs_object_client_test.go:232
              Error:          Not equal:
                              expected: true
                              actual  : false
              Test:           TestTCPErrs/transport_connect_timeout_exceeded,_retryable
```